--- 

- name: Deploy Portainer
  hosts: localhost
  become: yes
  
  
  tasks:
    - name: Create Portainer Docker volume
      community.docker.docker_volume:
        name: portainer_data

    - name: Run Portainer container
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:lts
        state: started
        restart_policy: always
        published_ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data







# - name: Install portainer
#   become: true
#   community.docker.docker_container:
#     name: "{{ portainer_name }}"
#     state: started
#     container_default_behavior: no_defaults
#     image: "{{ portainer_image }}"
#     restart_policy: always
#     ports:
#       - "{{ portainer_external_port }}:9443"
#     volumes:
#       - "{{ portainer_volume_name }}:/data"
#       - /var/run/docker.sock:/var/run/docker.sock


# docker volume create portainer_data

# docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:lts
