---
- name: Install and configure base C-Disk image
  hosts: all
  become: true #can later change this to false and have each main.yml contain it's own root/local permissions 
  gather_facts: true

  # vars_files:
  #   - vars/main.yml

  tasks:

    - name: Certificate set up
      include_tasks: tasks/certs/main.yml
      tags: certs

    - name: Docker install
      include_tasks: tasks/docker/main.yml
      tags: docker

    - name: Node Red install
      include_tasks: tasks/nodered/main.yml
      tags: node

    - name: Gitlab
      include_tasks: tasks/gitlab/main.yml
      tags: gitlab

    - name: Beekeeper install
      include_tasks: tasks/beekeeper/main.yml
      tags: beekeeper
