---
- name: Install and configure base C-Disk image
  hosts: all
  become: true #can later change this to false and have each main.yml contain it's own root/local permissions 
  gather_facts: true

  # vars_files:
  #   - vars/main.yml

  tasks:
    - name: Include Beekeeper installation tasks
      include_tasks: tasks/beekeeper/main.yml
      tags: beekeeper

    - name: Include Docker installation tasks
      include_tasks: tasks/docker/main.yml
      tags: docker

    - name: Include certificate setup tasks
      include_tasks: tasks/certs/main.yml
      tags: certs
